### ISSUE TITLE
Media library thumbnails broken with Netlify CMS 2.5

### ISSUE THREAD

**Issue by turijs** [ADARTA/netlify-cms-components#10]
After upgrading to version 2.5 of the CMS I noticied the thumbnails in the media library are just placeholders:
<img width="861" alt="thumbnail-placeholders" src="https://user-images.githubusercontent.com/17010148/53698357-9334f700-3da9-11e9-8a96-da38a45adfdb.png">

I dug into this a bit and noticed a couple issues:
* `FileSystemBackend.getMedia()` needs to return an actual `id` for each file (`sha` is coming through as undefined)
* `FileSystemBackend.getMedia()` needs to either provide a `getDisplayURL()` function, or declare `urlIsPublicPath: true` for each file

I was able to get the thumbnails working again by setting `urlIsPublicPath` to `true` and  `id` to `path` (though I realize that might not make an ideal choice of ID).

Thanks!

**Comment by talves** [comment]
Thanks for the heads up. I knew about the change, but did not realize it would affect this backend. Glad there is a workaround for now.

There are some issues with `netlify-cms` widget and backends (#11) using multiple instances  of React that will take precedence over this issue.

I will probably get back to this issue once there is a solution for #11. There may be a requirement after that change to only use manual init to use `backend-fs`, but am working that out now.

**Comment by talves** [comment]
0.4.2 will fix this, but 0.4.2 will not be able to be used with the current version of `netlify-cms`, because this backend requires a single instance of React.

There is a explanation in the [readme.md](https://github.com/ADARTA/netlify-cms-components/tree/master/packages/netlify-cms-backend-fs)

**Comment by talves** [comment]
Ah, the id is tied to this on certain setups also. I hate when changes to api's are not documented 😆... Reopening

**Comment by turijs** [comment]
Thanks for the update!

**Comment by talves** [comment]
No Problem. This release will not really work yet with the latest version of netlify-cms, but hopefully it will not be too long until that is fixed.
