### ISSUE TITLE
Use with Gatsby

### ISSUE THREAD

**Issue by burgerboydaddy** [ADARTA/netlify-cms-components#16]
This is not a bug report but ask for help.
I'm trying to integrate gatsby and netlify (with fs file system as backend), but all I receive is "file-system" backend is not registered.
Any example of how to link with Gatsby?

Thanks in  advance

**Comment by talves** [comment]
Have you seen this readme? https://github.com/ADARTA/gatsby-starter-netlify-cms

**Comment by talves** [comment]
The backend is still in beta until we get the `netlify-cms-app` change in the official plugin ([track here][1])

You can try my beta plugin [@talves/gatsby-plugin-netlify-cms][2] that is setup for it.


[1]: https://github.com/gatsbyjs/gatsby/pull/13036
[2]: https://github.com/talves/gatsby-plugin-netlify-cms

**Comment by burgerboydaddy** [comment]
Thanks for fast response.
I did check https://github.com/ADARTA/gatsby-starter-netlify-cms and I did exactly according to it but still have error accessing /admin
Error loading the CMS configuration
Config Errors:
Error: Backend not found: file-system

I will check the mentioned beta plugin.

**Comment by talves** [comment]
Without seeing your code it is hard to say where the failure is coming from. Sorry.

**Comment by burgerboydaddy** [comment]
Hello again,
I managed to get https://github.com/ADARTA/gatsby-starter-netlify-cms.git to work.
It took some time to get it to work (packages were little too old, but it works now.
Thanks for the help and guidelines.

**Comment by talves** [comment]
@burgerboydaddy yeah, we have been moving fast on getting some compatible libraries out there, so things break fast on these examples also.

Glad you got it working.
