### ISSUE TITLE
Bug in composeFileTree with simple path

### ISSUE THREAD

**Issue by PetrSnobelt** [ADARTA/netlify-cms-components#18]
If you use path without directory (like `file: "companypage.json"`) in config, code below cause infinite loop. Works fine with (file: "/data/companypage.json")
https://github.com/ADARTA/netlify-cms-components/blob/master/packages/netlify-cms-backend-fs/src/API.js#L109

**Comment by talves** [comment]
Closing: https://github.com/ADARTA/netlify-cms-components/issues/21#issuecomment-700221094
