### ISSUE TITLE
Provide custom AuthLogin component

### ISSUE THREAD

**Issue by damassi** [ADARTA/netlify-cms-components#3]
Right now this is hardcoded into the library and makes some assumptions (such as where the logo should be). It would be nice for consumers of the lib to be able to pass in their own. Thoughts? 

Lib works great by the way! Was able to extract it quite easily into our Gatsby install.

**Comment by talves** [comment]
There are some options for you if you are a React developer.

One would be to extract out the backend to it's own library and modify the auth component yourself. Ability to register a backend does work today.

Pros:

 - Have full control of auth customization
 - If have urgency, this can be done today


Cons:
 - Would have to make sure to upgrade library if backend API changes on a major version change
 - Will assume some knowledge of the code

**Comment by damassi** [comment]
I definitely don't want to extract the backend -- `netlify-cms-backend-fs` is nice here as a node module that I can import, and by extracting things get out of sync with updates etc. Not worth it for a single react component :)  

Could we update the api to provide some configuation? Something like: 

```js
// implementation.js
import { DefaultAuthenticationPage } from './DefaultAuthenticationPage'

export function initBackend(config) {
  const { 
    AuthenticationPage = DefaultAuthenticationPage
  } = config 

 class FileSystemBackend {
    ... 
    authComponent() {
      return AuthenticationPage
    } 
    ... 
  } 

  return FileSystemBackend
}
```

(As an aside, was able to add to a Gatsby install like so: https://github.com/artsy/palette/pull/226/files)

**Comment by talves** [comment]
Sorry, @damassi I did not even notice this was on my own repo. I am embarrassed 😳 now. I thought the issue came from the NetlifyCMS repo. 😜

Of course, I understand what you are saying. Let me give this some thought once I get some time.

**Comment by talves** [comment]
Closing: https://github.com/ADARTA/netlify-cms-components/issues/21#issuecomment-700221094
