### ISSUE TITLE
Standalone backend with non javascript CMS

### ISSUE THREAD

**Issue by Benoss** [ADARTA/netlify-cms-components#7]
I have issues to login with a local Stand Alone Server.
My CMS backend is in Python and works with the gitlab backend. I can't manage to use the localfs backend

My localserver.js
```
var express = require('express')
var app = express()

var netifly  = require("netlify-cms-backend-fs/dist/fs/fs-express-api");
netifly(app)

var port = 3000;
app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```
Then I run this with node localserver.js

This is my config.yml
```
backend:
  name: gitlab
  repo: myname/myrepo
  auth_type: implicit
  app_id: 123123123123123
  api_root: http://localhost:3000/api
```

After clicking on the gitlab button I am getting a 500 because on this URL: http://localhost:3000/api/user?ts=1549598004241
There is no route for /api/user defined in fs-express-api.js is there a way for me to bypass login when using the FileSystemBackendClass ?
The page is still showing login with gitlab and for some reason not using FileSystemAuthenticationPage component

**Comment by talves** [comment]
You understand this is not a replacement for a self-hosted back-end. This is used to write to the file system for local Dev.

Register the back end like this example
 https://github.com/ADARTA/netlify-cms-server-example/blob/master/example/admin/index.html

Then set up your config.yml like so

    backend:
      name: file-system
      api_root: /api

**Comment by Benoss** [comment]
Yeah I did realise that after writing the issue. But it seams that the main config file is read and used before the registration happen as I am getting unknown backend 'file-system'

**Comment by talves** [comment]
Where are you registering the backend. I did not see it.

**Comment by Benoss** [comment]
In the html (following your example). Will send a screenshot shortly

**Comment by talves** [comment]
Without seeing code, I will not be able to say.

**Comment by Benoss** [comment]
```
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <meta name="date" content="2015-09-09" />
  <title>Content Manager</title>
  <!-- Include the styles for the Netlify CMS UI, after your own styles -->
  <link rel="stylesheet" href="https://unpkg.com/netlify-cms@latest/dist/cms.css" />
    <base href="/admin/">
</head>
<body>
    <script src="https://unpkg.com/netlify-cms@latest/dist/netlify-cms.js"></script>
    <script src="https://unpkg.com/netlify-cms-backend-fs@^0.3.0/dist/index.js"/>
    <script>
      CMS.registerBackend("file-system", FileSystemBackendClass)
    </script>
</body>
</html>
```

```
backend:
  name: file-system
  api_root: http://localhost:3000/api
  login: false
```
![image](https://user-images.githubusercontent.com/1436055/52540896-b9dbbf80-2df3-11e9-9760-9fd69f6859ea.png)

**Comment by talves** [comment]
what happens when you hit:

http://localhost:8000/admin/

What is the url of the api server started to?
Also what url are you serving up your index.html to?

**Comment by Benoss** [comment]
I am using Pelican (A python CMS) listening on port 8000
Starting express with fs-express-api on port 3000
Serving /admin/ as a static folder with index.yml and config.yml in it
No problem with a gilab backend, if you try just the html I posted and the config.yml in a blank project
I think the issue is because <script src="https://unpkg.com/netlify-cms@latest/dist/netlify-cms.js"></script> is loading the CMS before the registration

**Comment by Benoss** [comment]
I managed to make it work now!
Threre is a settings in netifly-cms.js to not init the CMS (window.CMS_MANUAL_INIT = true)

my `/admin/index.html` looks like this

```html
<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Content Manager</title>
    <link rel="stylesheet" href="https://unpkg.com/netlify-cms@latest/dist/cms.css"/>
</head>
<body>
    <script>
        // Force Netifly not to autostart before registration
      window.CMS_MANUAL_INIT = true;
    </script>
    <!-- Import netifly cms and the file system backend from CDN !-->
    <script src="https://unpkg.com/netlify-cms@latest/dist/netlify-cms.js"></script>
    <script src="https://unpkg.com/netlify-cms-backend-fs@latest/dist/index.js"></script>
    <script>
        // Register file-system in the CMS
      CMS.registerBackend("file-system", FileSystemBackendClass)
        // Init the CMS
      initCMS()
    </script>
</body>
</html>
```

Then I had a cors issue with express because the static website and the fs API are not on the same port but easy fix with 'cors' package

`local_cms.js` at the root of my project look like this (launching it with `node local_cms.js`)

```javascript
var express = require('express')
var cors = require('cors')
var netifly = require("netlify-cms-backend-fs/dist/fs/fs-express-api")

var app = express()
app.use(cors())
netifly(app)

var port = 3000;
app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```
And my backend in `/admin/config.yml` looks like this one:

```yaml
backend:
  name: file-system
  api_root: http://localhost:3000/api
  login: false
```
Can create a pull request to add this to the readme if you want

**Comment by talves** [comment]
Good catch. I actually contributed to the manual init flag and this workflow in `netlify-cms`. I should have thought about these conditions, but in most cases, I change it in a custom backend, so sorry I did not think of it right away 😞.

I will add it to the Readme right away and change my example server app and add it to that readme also.

The `cors` issue is always going to be an issue when running on diff endpoints. I will put it in as a note and comments. Good idea.😀 👍

**Comment by talves** [comment]
Closing, see: [new readme here][1] and [on server example][2]

[1]: https://github.com/ADARTA/netlify-cms-components/blob/master/packages/netlify-cms-backend-fs/README.md
[2]: https://github.com/ADARTA/netlify-cms-server-example/blob/master/README.md

**Comment by SleepProgger** [comment]
First of all thanks for this project.
There is still no mention about cors in the README tho. Would be awesome if that ould be added as i just spend 10 minutes trying to figure out what went wrong.

I used 
```
var allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type');
    next();
}
app.use(allowCrossDomain);
```

instead of the cors module btw.

**Comment by talves** [comment]
@SleepProgger Your solution is probably the easiest. I did link it on the server example, but will add your example on the main one here. Thanks.
